name: CI

env:
    DOCKER_BUILDKIT: 1

on:
    push:
        branches: [ main, develop ]
        tags:
            - 'v[0-9]+.[0-9]+.[0-9]+'
            - '[0-9]+.[0-9]+.[0-9]+'
    pull_request:
        branches: [ main, develop ]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

jobs:
    publish_docker_api:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        strategy:
            matrix:
                node-version: [ 18.x ]
        steps:
            -   uses: actions/checkout@v3
            -   name: Set Branch
                id: short_ref
                run: echo ::set-output name=short_ref::${GITHUB_REF#refs/*/}
            -   name: Set git_url_commit
                id: git_url_commit
                run: echo ::set-output name=git_url_commit::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/commit/${GITHUB_SHA}
            -   name: Set git_url_ci_run
                id: git_url_ci_run
                run: echo ::set-output name=git_url_ci_run::${GITHUB_SERVER_URL}/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}
            -   name: Set git_commit
                id: git_commit
                run: echo ::set-output name=git_commit::${GITHUB_REPOSITORY}/${GITHUB_SHA}
            -   name: Set git_ci_run
                id: git_ci_run
                run: echo ::set-output name=git_ci_run::${GITHUB_REPOSITORY}/${GITHUB_RUN_ID}

            -   name: Docker Registry login
                run: docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}

            -   name: Build image `api`
                run: |
                    docker image build -t ghcr.io/elbakerino/baistro -f Dockerfile .

            -   name: Publish image `api` as `develop`
                if: github.ref == 'refs/heads/develop'
                run: |
                    docker tag ghcr.io/elbakerino/baistro ghcr.io/elbakerino/baistro:develop
                    docker push ghcr.io/elbakerino/baistro:develop
            -   name: Publish image `api` as `main`
                if: github.ref == 'refs/heads/main'
                run: |
                    docker tag ghcr.io/elbakerino/baistro ghcr.io/elbakerino/baistro:main
                    docker push ghcr.io/elbakerino/baistro:main
            -   name: Publish image `api` tagged & latest
                if: startsWith(github.ref, 'refs/tags/')
                env:
                    RELEASE_VERSION: ${{ steps.short_ref.outputs.short_ref }}
                run: |
                    docker tag ghcr.io/elbakerino/baistro ghcr.io/elbakerino/baistro:$RELEASE_VERSION
                    docker push ghcr.io/elbakerino/baistro:$RELEASE_VERSION
                    docker tag ghcr.io/elbakerino/baistro ghcr.io/elbakerino/baistro:latest
                    docker push ghcr.io/elbakerino/baistro:latest
